language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  include:
    - php: 5.5
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - composer self-update

install:
  - if [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then composer require zendframework/zend-crypt:^2.5 --dev --no-update; fi;
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
