language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

before_install:
- sudo apt-get update
- sudo apt-get install make build-essential automake php5-dev php-pear
- if [ "$TRAVIS_PHP_VERSION" < "7.2" ]; then git clone git://github.com/jedisct1/libsodium.git && cd libsodium && git checkout 1.0.15 && ./autogen.sh && ./configure && make check && sudo make install && cd ..; fi;
- pecl channel-update pecl.php.net
- if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then pecl install libsodium-1.0.7; fi;
- if [ "$TRAVIS_PHP_VERSION" > "5.6" -a "$TRAVIS_PHP_VERSION" < "7.2" ]; pecl install libsodium;; fi;

install:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer remove "paragonie/halite" --dev --no-update $COMPOSER_FLAGS; fi;
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require "paragonie/halite" --dev --prefer-source $COMPOSER_FLAGS; fi;
  - composer install --prefer-source $COMPOSER_FLAGS

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
